name: Build cmake system

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker pull ghcr.io/noaa-gfdl/gfdl-vortextracker/vortex-ci-gnu:gcc14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Build
      run:  cmake ..
    - name: Compile
      run:  make
    - name: Run tests
      run:  make test