name: Build cmake system

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/noaa-gfdl/gfdl-vortextracker/vortex-ci-gnu:gcc14

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Make & move into build dir
      working-directory: /code
      run: |
           cmake .
           make
           make test
