name: Build cmake system

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./compile/src_code
    container:
      image: ghcr.io/noaa-gfdl/gfdl-vortextracker/vortex-ci-gnu:gcc14.2.0
      env:
        NetCDF_INCLUDE_DIRS: "/opt/views/view/include/"

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Build & compile code
      run: |
        mkdir -p build && cd build
        cmake ..
        make
    - name: Run tests
      run: |
        cd build
        make test
